{"name": "Pecan Date Butter", "ingredients": [" pound pecan halves or pieces", " pitted dates, about ", " of a neutral oil, we used grapeseed oil", " Himalayan pink salt*"]}
{"name": "Four Cheese Baked Manicotti", "ingredients": [" dry/uncooked manicotti shells", " extra virgin olive oil", " onion, finely chopped", " fresh garlic, minced", " pounds whole milk ricotta cheese", " freshly grated Parmesan cheese, divided", " freshly grated Romano cheese", " grated mozzarella cheese, divided", " fresh flat leaf parsley, chopped", " fresh basil, chopped", " fresh oregano, chopped", " beaten eggs", " kosher salt", " white pepper", "-quart tomato sauce, "]}
{"name": "Cinnamon Roll Bread Pudding with Bourbon Sauce", "ingredients": ["", " cinnamon rolls that are a day-old, cut into large cubes (see ). If buying cinnamon rolls, you will need just shy of four pounds ()", " milk", " eggs", " egg yolk", " heavy cream", " sugar", " vanilla", " allspice", "Pinch of freshly ground nutmeg", " additional cup of milk", " butter, divided", "", " ( or 1 stick) of butter", " brown sugar", " egg", " heavy cream", " bourbon", " vanilla extract", "Pinch of nutmeg"]}
{"name": "Spinach Pesto Pinwheels", "ingredients": [" 17.3-ounce box puff pastry sheets ( sheets)", " walnuts", " baby spinach", " chopped fresh garlic", " freshly grated Parmesan cheese", " freshly grated Romano cheese", " kosher salt", " freshly grated black pepper", " extra virgin olive oil", " roasted red bell pepper, chopped", " pound sharp cheddar cheese, shredded", " egg beaten with one teaspoon of water"]}
{"name": "Cinnamon Rolls with Bourbon-Soaked Raisins", "ingredients": [" bourbon", " raisins", " all-purpose flour, divided (plus more as needed)", " package dry yeast ()", " of milk", " butter", " extra virgin olive oil", " sugar", " salt", " eggs", " brown sugar", " flour", " cinnamon", " stick melted butter", " powdered sugar", "A few teaspoons of milk"]}
{"name": "No-Bake Eggnog Cream Pie", "ingredients": ["", " whole graham crackers (1 sleeve or about  after crushing)", " granulated sugar", " brown sugar", " stick butter melted, 8 tablespoons", "", " cream cheese, softened", " ground cinnamon", " freshly grated nutmeg", " 14-ounce can sweetened condensed milk", " golden eggnog", " 1.5-ounce box sugar free Jell-O cheesecake mix", " 1.5-ounce box sugar free Jell-O vanilla pudding mix", " heavy whipping cream", "Plus cinnamon and nutmeg for dusting"]}
{"name": "Perfect French Toast", "ingredients": [" loaf of unsliced French Brioche, approximately 1 pound in weight", " large eggs", " granulated sugar", "Pinch of salt", " ground cinnamon", "Few grinds nutmeg", " vanilla extract", " whole milk", " butter, plus more to serve with each portion", " of warmed maple syrup"]}
{"name": "Pomfresca Cocktail", "ingredients": [" pomegranate juice (we used Pom Wonderful)", " Fresca (Original Citrus flavor)", " vodka"]}
{"name": "Russian Chicken", "ingredients": [" large 5-6 pound cut-up chicken (\u2013 bone-in pieces)", " kosher salt", " freshly ground black pepper", " butter", " olive oil", " large Granny Smith apples, cored and cut into s. Keep in a bowl of water with a little lemon juice to stop them from turning brown until ready to use.", " large sweet onion, sliced thickly", " orange skin cut into slivers (from  large navel oranges)", " white wine", " orange juice, squeezed from the two navel oranges"]}
{"name": "Pomfresca Float", "ingredients": [" pomegranate juice (we used Pom Wonderful)", " Fresca (Original Citrus flavor)", " small scoop vanilla ice cream"]}
{"name": "Ham and Cheese Pinwheels", "ingredients": [" 17.3-ounce box puff pastry sheets ( sheets)", " spicy brown mustard, we used Guldens", " mayonnaise", " fresh thyme, chopped", " fresh garlic, finely minced", " Black Forest ham, thinly sliced", " sharp white cheddar cheese, shredded", " Jarlsberg Swiss cheese, shredded"]}
{"name": "Italian Beef and Sausage Pie", "ingredients": ["Vegetable shortening or butter to grease a 9-10 inch spring form pan (pan should be at least 2 \u00bd inches deep)", " extra virgin olive oil, divided", " pound ground beef", " pound Italian sweet sausage removed from casing", " large sweet onion, diced into large half inch pieces, about ", " large green Bell pepper, diced into large half inch pieces, about ", " dry basil", " dry oregano", " kosher salt", " freshly ground black pepper", "Pinch red pepper flakes", " fresh garlic, minced", " tomato paste", "", " large eggs", " Greek full fat yogurt", " kosher salt", " baking powder", " all-purpose flour", "", " grated Parmesan cheese", " pound provolone cheese sliced", " large bunch scallions diced, about ", " mozzarella cheese, shredded"]}
{"name": "Oven-Roasted Horseradish Beef Brisket", "ingredients": ["-pound brisket of beef (*See Note below about smaller roasts)", " kosher salt", " coarsely ground fresh black pepper", " beef stock", " butter", " large sweet onion, sliced thick", " large garlic cloves, sliced", " Worcestershire sauce", " sprigs fresh thyme", " bay leaves", " mayonnaise", " drained horseradish"]}
{"name": "Sweet Potato Pudding", "ingredients": [" cooked  (about one large cooked sweet potato approximately \u2013 ounces)", " butter ( sticks), softened", " granulated sugar, divided", " large eggs", " almond flour", " vanilla extract", " salt", " heavy cream for whipping"]}
{"name": "Whipped Shortbread Cookies", "ingredients": ["Small jar of maraschino cherries, well drained", " pound butter, softened ( sticks)", " confectioner\u2019s sugar, sifted", " almond extract", " all-purpose flour", " corn starch", "Sprinkles for decorating"]}
{"name": "Italian Meat Ragu", "ingredients": ["\u2013 pound chuck roast", " kosher salt", " freshly ground black pepper", " extra virgin olive oil", " pancetta, diced small", " pound sweet sausage, removed from casing but left in the sausage shape and cut in half across the middle", " red onion, diced", " carrots, diced", " celery, diced", " fresh garlic, minced", " 6-ounce can tomato paste", " bold red wine, such as Merlot", " chicken broth or stock", " 28-ounce can crushed tomatoes", " small bunch fresh thyme", " large sprigs fresh parsley", " bay leaves", " pound pappardelle pasta", " freshly grated Parmesan cheese, divided"]}
{"name": "Chicken Boscaiola", "ingredients": [" pound boneless skinless chicken breasts, cut into bite-sized pieces", " extra virgin olive oil", " butter, divided", " pound bacon, chopped (about  slices)", " baby Bella sliced mushrooms (about \u2013 ounces)", " onions, diced", " fresh garlic, minced", " dry sherry", " heavy cream", " sour cream", " salt", " freshly ground black pepper", " dried oregano", " dried basil", " fresh Italian flat-leaf parsley, chopped", " grated Parmesan cheese", " pound fettuccine", "Additional chopped, Italian flat-leaf parsley, for garnish"]}
{"name": "Perfect Mashed Potatoes", "ingredients": [" kosher salt to salt water", " pounds Russet potatoes (about 4)", " pound yellow potatoes such as Yukon Gold", " whole milk or light cream", " sticks salted butter ( pound)**", " white pepper", " garlic powder", "**If you use unsalted butter instead, taste final mashed potatoes and add more salt as needed."]}
{"name": "Turkey & Stuffing Turnovers", "ingredients": [" cold leftover , chopped", " cold leftover , broken up", " cold leftover", " leftover ", " 17.2-ounce box ( ready-to-bake) Pepperidge Farm Puff Pastry Sheets", " egg"]}
{"name": "Juicy Roast Turkey", "ingredients": ["One turkey, 12-15 pounds", " medium carrots, sliced", " celery stalks, cut up into pieces", " large onion, quartered", " butter, 1 stick divided", " kosher salt, plus more as needed", " freshly ground black pepper, plus more as needed", " chicken broth, divided"]}
{"name": "Acorn Squash with Sausage & Rice Stuffing", "ingredients": [" uncooked brown rice", " chicken or vegetable stock", " water", " butter", " kosher salt", " large acorn squash (try to pick squash that are short and squat instead of long and pointy tipped)", " extra virgin olive oil, divided", " sweet onion, diced medium", " fresh sage chopped fine, or half that of dried", " kosher salt", " freshly ground black pepper", "Pinch red pepper flakes", " pound sweet Italian sausage, removed from casings", " fresh or frozen cranberries", " fresh kale leaves chopped fine", " water", " freshly grated Parmesan cheese, plus more for tops"]}
{"name": "Homemade Applesauce", "ingredients": [" apple juice", " water", " sugar*", " ground cinnamon", "Few grinds fresh nutmeg", " lemon zest (zest very fine)", " lemon juice", "Pinch kosher salt", " pounds apples (we used Macintosh and Shizuka -a cross between a Golden Delicious and Indo)"]}
{"name": "Leftover Turkey Noodle Soup", "ingredients": [" turkey stock, see our ", "  (affiliate link)", " extra virgin olive oil", " onion, diced half inch", " celery, diced half inch", " carrot, diced half inch", " fresh thyme or half that of dried", "\u2013 cups leftover turkey, cut into bite sized pieces"]}
{"name": "Soft Almond Sugar Cookies", "ingredients": [" butter, softened", " granulated sugar", " eggs, whites and yolks separated", " almond extract", " vanilla extract", " all-purpose flour", " baking powder", " salt", " milk", " orange juice", "", " confectioner\u2019s sugar", " cream or milk", " almond extract", " sliced almonds"]}
{"name": "Pasta with Ground Turkey & Broccoli", "ingredients": ["-pound head of broccoli, or  small heads", " extra virgin olive oil", " sweet onion, diced (such as Vidalia)", " red bell pepper, diced (about  large pepper)", " minced garlic", "Zest of  lemon", " pounds ground turkey", " kosher salt", " freshly grated black pepper", " pound curly dry pasta, also called cavatappi", " lemon juice", " chopped fresh basil, plus more for garnish", " chicken stock", " freshly grated Parmesan cheese, plus more for garnish"]}
{"name": "Perfect Pie Crust", "ingredients": [" butter", " vegetable shortening", " all-purpose flour", " salt", " granulated sugar", "\u2013 tablespoons ice cold water"]}
{"name": "Turkey Pot Pie", "ingredients": [" 10-ounce bags fresh, raw pearl onions (frozen may also be used)", " turkey stock (see )", " pound carrots sliced thick and on the bias, cut to bite- sized pieces (about )", " pound peeled red potatoes, cut to bite-sized pieces (about )", " fresh chopped thyme or  dry", " fresh chopped parsley or  dry", " kosher salt, depending on how salty your stock is", " white pepper", "Few grinds freshly grated nutmeg", " dry mustard powder", " Worcestershire sauce", "Few drops Tabasco sauce", " heavy cream", " frozen peas", " pounds , cut into bite-sized pieces", " gravy seasoning sauce, such as Kitchen Bouquet or Gravy Master", " butter", " flour", " 12-inch rounds of ", " egg", " sugar"]}
{"name": "Lemon Meringue Pie", "ingredients": [" 14-ounce pie dough for a 10\u201d glass pie plate (see our  and weigh out  using a )", "", " egg whites (about \u2013 large eggs separated)", " cream of tarter", " vanilla extract", " granulated sugar", "", " water", " granulated sugar", " corn starch", " lemon zest grated fine (about  lemons)", " freshly squeezed lemon juice (about \u2013 lemons)", " salt", " egg yolks in a medium to large bowl (about  large eggs separated)", " butter cut into pats ( stick)"]}
{"name": "Beef Birria Tacos", "ingredients": ["", " pounds beef shank*", " pounds beef chuck", " kosher salt", " freshly ground black pepper", "", " dried Guajillo chiles**", " dried California chiles", " plum tomatoes", " 7-ounce can chipotle in adobo (I used only  can to keep it mild)", " garlic, chopped", " Mexican Oregano", " ground cumin", " apple cider vinegar", "", " extra virgin olive oil", " white onion, diced", " cinnamon stick", " bay leaves", " minced garlic", " beef stock or broth", "", " 6-inch corn tortillas (you could also use flour tortillas)", " Cotija cheese, crumbled", " small bunch cilantro leaves", "\u2013 fresh jalapenos, sliced thin", " finely diced white onion", "\u2013 fresh limes cut into wedges"]}
{"name": "Southwestern Potatoes", "ingredients": [" pounds little yellow potatoes (I used bite-sized Honey Gold brand)", " kosher salt to salt the potato water", " large ", " butter, divided", " white onion, diced", " minced fresh garlic", " kosher salt", "Few grinds black pepper", "Cotija cheese, crumbled for garnish", "Fresh chopped cilantro, for garnish"]}
{"name": "Churros", "ingredients": [" water", " butter", " salt", " granulated sugar", " all-purpose flour", " whole eggs", "Vegetable oil for frying.", "", " granulated sugar", " ground cinnamon", " semi-sweet chocolate morsels", " whole milk"]}
{"name": "Eye of the Round Roast", "ingredients": ["-pound eye of round beef roast, preferably with a fat cap", " kosher salt", " freshly ground black pepper", " fresh garlic, chopped", " fresh thyme leaves, chopped", " Dijon mustard", " extra virgin olive oil, divided", "", "Pan drippings", " strong red wine such as Merlot", " beef broth or stock", " gravy flavor color", " butter, softened", " all-purpose flour", "Salt and pepper, as needed"]}
{"name": "Lidia\u2019s Pizza Rolls", "ingredients": [" pounds (32 ounces) pizza dough (make our ), or use store bought", " large bunch broccoli rabe; after cutting and steaming, 2 cups", " pound sweet Italian sausage, removed from casings", " extra virgin olive oil", " large sweet onion cut into thick slices", " large leeks, white only cleaned of sand and diced large ( \u2013  cups)", " large garlic cloves sliced", "Pinch red pepper flakes", " kosher salt", " freshly ground black pepper", " freshly grated Parmesan cheese", " pound ricotta cheese (some brands are , which is fine)", " beaten egg"]}
{"name": "Scalloped Ham and Potato Casserole", "ingredients": [" pounds peeled Russet potatoes*", " butter", " chopped onion", " chopped fresh parsley", " chopped fresh thyme or  dry", " all-purpose flour", " heavy cream", " salt", " white pepper", "Few drops hot sauce such as Tabasco, Cholula or Sriracha", " Worcestershire sauce", "Few grinds fresh nutmeg", " Colman\u2019s dry mustard", " shredded sharp cheddar cheese, divided", " pound Black Forest or Virginia ham, sliced thin", " shredded mozzarella cheese (not fresh mozzarella)"]}
{"name": "Homemade Buttermilk", "ingredients": [" freshly squeezed lemon juice**", " whole milk (You can also use 1% or 2% milk fat)"]}
{"name": "Apple Cobbler", "ingredients": [" pounds mixed apples (Braeburn and Granny Smith), about 9 apples*", "Juice of  large lemon", " butter", " granulated sugar", " brown sugar", " ground cinnamon", " ground ginger", "Few grinds fresh nutmeg", " water", " all-purpose flour", "", " all-purpose flour", " baking powder", " baking soda", " salt", " plus 1 teaspoon granulated sugar, divided", " buttermilk (make our , or use store-bought)", " melted butter, divided", "Serve with "]}
{"name": "Apple Crisp Pizza", "ingredients": [" box frozen puff pastry sheets ( sheets), thawed. (.)", " baking apples (we used  Granny Smith and  Braeburn)", "Juice from  lemon", " brown sugar", " granulated sugar", " ground cinnamon", " ground dry ginger", "Few grinds fresh nutmeg", " all-purpose flour", "", " all-purpose flour", " brown sugar", " rolled oats (not quick oats)", " ground cinnamon", " salt", " butter, softened", " small jar or bottle "]}
{"name": "Baked Carrot Casserole", "ingredients": [" pounds carrots, peeled and sliced", " butter", " red bell pepper diced", " sweet onion, diced", " kosher salt", " freshly ground black pepper", " granulated sugar", " all-purpose flour", " whole milk", " egg beaten", " flat leaf parsley, chopped"]}
{"name": "Chicken Exquisito", "ingredients": [" pound pasta (use your favorite, we used vermicelli)", " \u2013  pounds boneless skinless chicken breast halves", " kosher salt", " freshly ground black pepper", " all-purpose flour", " large eggs", " whole milk", " extra virgin olive oil, divided", " cold butter, divided", " fresh garlic, finely minced", " good quality brandy", " good quality sweet Marsala wine", " low sodium chicken stock", " shredded mozzarella cheese", " fresh parsley, chopped for garnish", " lemon, cut into  wedges, for garnish"]}
{"name": "Innkeeper\u2019s Pie", "ingredients": [" 9-inch , unbaked", " chopped walnuts, toasted (pecans or pine nuts could also be substituted)", "", " water", " unsweetened chocolate", " granulated sugar", " butter", " vanilla", "", " all-purpose flour", " baking powder", " salt", " butter, softened", " granulated sugar", " large egg", " whole milk", " vanilla", " of heavy cream to whip and serve over each slice, or buy already whipped cream."]}
{"name": "Keto Sheet Pan Italian Meatloaf", "ingredients": [", but follow the directions below in Step 1", " extra-virgin olive oil", " onion, finely diced", " green bell pepper, finely diced", " fresh garlic, minced fine", " pounds 80/20 ground beef", " pound Italian mild sausage, out of casing", " eggs, beaten", " kosher salt", " freshly ground black pepper", " dry oregano", " dry basil", " freshly grated Parmesan cheese", " of our\u00a0  (made without sugar), or your favorite pizza sauce", " shredded mozzarella cheese"]}
{"name": "Chicken & Penne with Basil Parmesan Cream Sauce", "ingredients": [" pounds boneless skinless chicken breasts", " kosher salt", " freshly ground black pepper", " extra virgin olive oil", " butter", " all-purpose flour", " heavy cream", " bay leaves", " freshly grated Parmesan cheese", " kosher salt", " white pepper", " large leaves fresh basil*", " fresh nutmeg", " dry mustard", "Large pinch red pepper flakes", " pound penne pasta", "Additional chopped fresh basil for garnish", "Additional grated Parmesan cheese for garnish"]}
{"name": "Chicken Mulligatawny Soup", "ingredients": [" extra virgin olive oil, divided", " pounds chicken thighs, trimmed and cut into bit sized pieces", " butter", " onion, diced", " celery, diced", " carrots, cut into bite-sized pieces", " fresh garlic, minced", " all-purpose flour", " ", " ", " ground cumin", " dry thyme", " white pepper", " kosher salt (adjust amount depending on how salty your chicken stock is)", "  if possible", " dry basmati or white rice", "Two large Granny Smith apples, cored, peeled and cut into bite sized pieces", " heavy cream"]}
{"name": "Pork Pot Roast", "ingredients": ["  or , homemade if possible", "\u2013-pound pork butt", "\u2013 teaspoons kosher salt", " \u2013 teaspoon freshly ground black pepper", " olive oil", " large onion, peeled and cut into  pieces", " large celery stalk cut into  pieces", " tomato paste", " bunch flat leaf parsley, wrapped with twine for easy removal", " pound carrots, peeled and cut into large slices on the bias", " pounds little potatoes, left whole", " large red onion cut into  pieces", " pound fresh green beans", " butter", " all-purpose flour ( plus )", " gravy browning and seasoning sauce (such as  or )"]}
{"name": "Zucchini Potato Torte", "ingredients": [" shredded zucchini (about  pounds or  medium zucchinis before shredding)", " extra virgin olive oil, divided", " butter", " sweet onion, diced", " shredded peeled Russet potato (about  pounds or  potatoes before shredding) * see instructions before shredding", " finely minced garlic (about  medium cloves)", " large eggs", " kosher salt", " freshly ground black pepper", "Few grinds fresh nutmeg", " freshly grated Parmesan cheese, divided", " plain bread crumbs"]}
{"name": "Lemon Snack Cake", "ingredients": ["", " all-purpose flour, measured by spooning the flour into a dry measuring cup", " granulated sugar", " salt", " baking soda", " eggs, beaten", " sour cream or full-fat Greek yogurt", " vegetable oil", "Zest of  lemons", " fresh lemon juice", "", " confectioner\u2019s sugar, measured by spooning the sugar into a dry measuring cup", "Zest of  lemon", " to  tablespoons fresh lemon juice"]}
{"name": "Reuben in a Bowl", "ingredients": ["", " to  pounds uncooked corned beef ( pounds of usable meat after cooking)", " medium onion quartered", " stalks celery, cut up", " carrots, cut up", "", " pound green cabbage, cored and cut into thin slices", " large onion, sliced", " pounds sauerkraut, drained (we used the fresh bagged sauerkraut from Boar\u2019s Head)", " slices marble or rye bread, crusts removed and cut into strips", " butter, melted", " , (or your favorite store-bought brand)", " pound Swiss cheese slices, cut into bite sized pieces"]}
{"name": "Asian Chicken Drumsticks", "ingredients": [" large chicken drumsticks, ours were 10 ounces each but any size will work*, 4-5 pounds", "", " buttermilk", " kosher salt", " powdered ginger", " ground cumin", " garlic powder", " paprika", " freshly ground black pepper", " Worcestershire sauce", " of flour, for coating", "Vegetable oil, for frying", "", " granulated sugar", " honey", " ", " soy sauce", " freshly squeezed lime juice", " sherry", " peanut oil", " sesame oil", " ginger powder", " water", " corn starch", "Sesame seeds, to sprinkle on finished chicken"]}
{"name": "Italian Beef Rollups", "ingredients": ["", " pounds beef chuck", " Kosher salt", " freshly ground black pepper", " extra virgin olive oil", " large onion sliced into thick slices", " tomato paste", " bold red wine such as merlot", " 14.5-oz can crushed tomatoes", " dry basil", " dry oregano", " beef stock or broth", "", " leftover mashed potatoes*", " all-purpose flour", " kosher salt", "", "Flour for rolling the roll-ups", " crushed tomatoes", " slices provolone cheese", " shredded mozzarella cheese", " freshly grated Parmesan cheese"]}
{"name": "Hamburger Stew", "ingredients": [" extra virgin olive oil", " pounds ground beef", " butter", " large stalks celery cut into \u201d pieces", " onion cut into \u201d pieces", " dry thyme", " freshly ground black pepper", " garlic, chopped", " tomato paste", " balsamic vinegar", " Worcestershire sauce", " all-purpose flour", " bold red wine, such as Merlot or Burgundy", " beef stock", " gravy seasoning and coloring sauce, such as Kitchen Bouquet or Gravy Master", " pounds carrots, peeled and cut into bite sized pieces", " pounds yellow potatoes, peeled and cut into bite sized pieces", " pound green beans cut into bite sized pieces", "Kosher salt, to taste"]}
{"name": "Roasted Pork Loin", "ingredients": ["-pound center cut pork loin, BRT (boned, rolled and tied) *see notes", " extra virgin olive oil, divided", " kosher salt, divided", " freshly ground black pepper, divided", " plus two tablespoons apple juice, divided", " pounds carrots peeled and left mostly whole, large pieces cut in half so all are uniform in size", " large Vidalia onions, peeled and cut into  sections each, 1 \u00bd pounds total", " sprigs fresh rosemary, left whole", " brown sugar, packed", " garlic powder", " spicy brown mustard (we like Guldens)", " chicken stock", " Russet potatoes, peeled and cut into bite sized pieces, three pounds total", " large Granny Smith apples, cored, peeled and cut into bite sized pieces", " butter", " all-purpose flour"]}
{"name": "Apple Slab Pie", "ingredients": ["", " all-purpose flour, divided", " granulated sugar, divided", " table salt, divided", " cold butter, divided ( sticks)", "Up to  cold water", "", " butter ( sticks)", " all-purpose flour", " granulated sugar", " brown sugar", " ground cinnamon", " ground ginger", " ground nutmeg", " water", " pounds Granny Smith apples (about  apples)", "Juice from  lemons (used to keep apples from oxidizing and will be discarded in the end)", " egg whisked to brush on crust before baking", "\u2013 tablespoons  or coarse sugar to sprinkle over top before baking* optional", " for serving."]}
{"name": "Spinach Lasagna Rollups", "ingredients": [" one-pound box dry lasagna noodles ( count)", " extra virgin olive oil", " onion, diced small", " minced garlic", " pound baby spinach", " kosher salt", " freshly ground black pepper", " 32-ounce tub whole milk ricotta cheese", " whole eggs", " shredded mozzarella cheese, divided", " Romano cheese, freshly grated", " tomato sauce ( or your favorite brand), divided", " Parmesan cheese, freshly grated"]}
{"name": "Grilled Pork Patty Melt", "ingredients": [" pounds sweet onion, such as Vidalia (\u2013 large onions)", " butter", " kosher salt", " freshly ground black pepper", "", " slices soft bread", " milk", " pound bacon ( slices usually), cut up small", " sweet onion, chopped", " garlic, chopped", " kosher salt", " black pepper", " dried thyme", " pounds ground pork", "", " large slices marble or rye bread", " softened butter", " full slices Swiss cheese"]}
{"name": "Bourbon Meatballs", "ingredients": ["", " panko bread crumbs", " whole milk", " pound ground beef", " pound ground pork", " whole eggs", " minced onion", " kosher salt", " freshly ground black pepper", " garlic powder", "", " brown sugar", " ketchup", " bourbon", " Worcestershire sauce", " hot sauce (we use Chalula because it is flavorful but mild)"]}
{"name": "Grilled Spaghetti Squash Steaks", "ingredients": [" large spaghetti squash", " extra virgin olive oil", " kosher salt", " freshly ground black pepper", " freshly grated Parmesan cheese"]}
{"name": "Oven Baked Chicken Thighs", "ingredients": ["\u2013 bone-in, skin-on chicken thighs OR 8-12 boneless, skinless chicken thighs", " extra virgin olive oil", " kosher salt", " freshly ground black pepper", " garlic powder", " paprika"]}
{"name": "Honey Mustard Dressing", "ingredients": [" Dijon mustard", " spicy brown mustard or deli-style mustard, your choice*", " mayonnaise", " honey", " apple cider vinegar", " freshly squeezed lemon juice", " kosher salt", " white pepper", " garlic powder", " extra virgin olive oil"]}
{"name": "Tiramisu", "ingredients": [" strong coffee, room temperature", " dark rum, divided", " ", " egg yolks (\u2013 yolks) \u2013 buy pasteurized eggs if you are nervous about consuming raw eggs", " granulated sugar", " salt", " 8-ounce packages mascarpone cheese", " heavy cream, chilled", " 7-ounce packages , any brand (total  pieces)", " Dutch process cocoa powder ("]}
{"name": "Minted Green Pea Puree", "ingredients": ["Half batch of our Pickled Red Onion, , for garnish", " 16-ounce bags frozen peas, thawed", " whole fresh mint leaves, packed (plus more for garnish if desired)", " water", " heavy cream", " butter", " loaf pumpernickel squares", "Butter or oil, for grilling the bread"]}
{"name": "Grilled Tomato Ciabatta", "ingredients": [" loaf Ciabatta bread", " very large thick garden tomatoes", "", " garlic, finely minced", " kosher salt", " freshly ground black pepper", " dry mint", " dry oregano", " dry basil", " red wine vinegar", " extra virgin olive oil", "", " can cannellini beans rinsed and drained (my can was 1 pound )", " minced fresh garlic", " fresh Italian flat leaf parsley", " fresh basil leaves", " kosher salt", " freshly ground black pepper", " red wine vinegar", " packed freshly grated Parmesan cheese", " extra virgin olive oil", "", "", " freshly grated Parmesan cheese", " packed fresh basil leaves", " kosher salt", " freshly grated black pepper", " mayonnaise", " extra virgin olive oil"]}
{"name": "Grilled Turkey Tenderloins", "ingredients": [" turkey tenderloins (about  pounds)", " brown sugar", " spicy brown mustard", " balsamic vinegar", " chili powder", " celery salt", " black pepper", " paprika", " garlic powder", " onion powder", " ground cumin", "Zest of  limes", " freshly squeezed lime juice", " of a light neutral oil such as grapeseed oil", "Vegetable oil to oil the grill grates"]}
{"name": "Perfect Baked Potatoes", "ingredients": ["Russet potatoes", "Olive oil", "Kosher salt", "", "Butter", "Sour cream", "Optional: Chives, shredded cheese, , chopped , or other favorite toppings."]}
{"name": "Gazpacho", "ingredients": [" long English cucumber, about , halved lengthwise and seeded, but not peeled, cut into large dice, about ", " red bell peppers, cored, seeded and cut into large dice, about ", " plum tomatoes large dice, about  or ", " small red onion diced, about 4-5 ounces or ", " garlic cloves, minced very fine or pushed through a garlic press, about ", " tomato juice", " white wine vinegar", " extra virgin olive oil", " kosher salt", " freshly ground black pepper", "Sour cream, for garnish (optional)"]}
{"name": "Copycat Rib Tickler Rub", "ingredients": [" ", " kosher salt", " granulated sugar", " freshly ground black pepper", " paprika", "Pinch of cayenne pepper"]}
{"name": "Oven Baked Country-Style Ribs", "ingredients": [" pounds country-style pork ribs, about  meaty ribs", " recipe of our ", " of your favorite BBQ sauce \u2013 we recommend this  or our "]}
{"name": "Peach Fritters", "ingredients": [" generous cups peeled and \u00bc-inch diced peaches (fresh, frozen or canned)", " plus 2 tablespoons all-purpose flour", " baking powder", " salt", " ground cinnamon", "Few grinds nutmeg", " allspice", " ground ginger", " whole eggs", " granulated sugar", " whole milk", " vanilla extract", "Vegetable oil, for frying", "Powdered sugar, for dusting"]}
{"name": "Grilled Zucchini Pizza", "ingredients": [" pounds (32 ounces) , store bought is fine", " , store bought is fine", " ricotta cheese", " shredded mozzarella cheese", " grated Parmesan cheese", " fresh flat leaf parsley, chopped", " kosher salt, divided", " freshly ground black pepper, divided", " extra virgin olive oil, divided", " small to medium zucchini, about \u2013 ounces each", " fresh mozzarella balls", "Fresh basil for garnish"]}
{"name": "Grilled Salmon Tacos with Pineapple Salsa", "ingredients": [" cooked salmon \u2013 we used leftovers from this ", "", " ripe pineapple, cleaned and diced", " red onion, diced", " cilantro, chopped", " fresh jalapeno, seeded and minced", " fresh lime juice", " fresh garlic, finely minced", " sea salt", "", " full fat sour cream", " ground coriander", " garlic powder", " kosher salt", "Few drops of hot sauce", " lime zest (zest then chop very small on a cutting board)", " fresh lime juice", "", " Roma tomatoes, diced", " large ripe avocado, diced", " six-inch flour or corn tortillas", "Additional cilantro for garnish, if desired"]}
{"name": "Zucchini Platz", "ingredients": [" butter to grease a 18X13 sheet pan", "", " pounds zucchini (about \u2013 medium zucchini)", " golden raisins", "Zest of  lemon", " lemon juice", " brown sugar", " cinnamon", "Few grinds nutmeg", "", " all-purpose flour", " granulated sugar", " baking powder", " ground cinnamon", " butter, melted", " chopped walnuts", "", " all-purpose flour", " granulated sugar", " teaspoon salt", " baking powder", " butter, melted", " whole milk", " whole eggs beaten", " vanilla extract"]}
{"name": "Broccoli Carrot Salad", "ingredients": [" pounds broccoli cut into small bite sized florets. I started with two very large heads to yield 1 \u00bd pounds of florets", " thinly sliced red onion", " shredded carrot (large holes of box grater), about two carrots", " ", " sundried tomatoes, chopped (ideally , if not, reconstitute in hot water first)", " mayonnaise", " apple cider vinegar", " pure maple syrup", " spicy brown mustard", " kosher salt", "", " walnut pieces", " soy sauce", " pure maple syrup", " smoked paprika"]}
{"name": "Swedish Tosca Cake", "ingredients": ["", "Butter and flour, to prepare the pan", " () unsalted butter, melted and cooled", " all-purpose flour", " baking powder", " kosher salt", " vanilla extract", " whole milk", " large eggs", " granulated sugar", "", " unsalted butter", " granulated sugar", " heavy cream", " all-purpose flour", "Pinch of kosher salt", " sliced almonds", " almond extract", " vanilla extract", "", "Whipped cream, optional", "Fresh strawberries, optional"]}
{"name": "Chile Colorado Burritos", "ingredients": [" prepared recipe , meat shredded", " prepared recipe ", " prepared recipe ", "\u201d flour tortillas, package of 8", " pound (16 ounces) Monterey Jack Cheese, shredded"]}
{"name": "Asian Grilled Salmon", "ingredients": [" pounds skin-on salmon filet", " Dijon mustard", " soy sauce", " extra virgin olive oil", " very finely minced fresh garlic"]}
{"name": "Grilled Balsamic Peaches", "ingredients": [" balsamic vinegar", " molasses", "\u2013 teaspoons freshly ground black pepper (you can add more or less based on your tastes but the pepper is really great against the other sweet flavors in this dish)", " ripe peaches", " vegetable oil"]}
{"name": "Quesadillas", "ingredients": [" 10-inch flour tortillas", " pounds Monterey Jack cheese, shredded", " 7-ounce can chopped mild green chilies, well drained", " fresh tomatoes, diced", " bunch scallions, tops and bottoms, chopped", " cilantro leaves", " optional , see note here*", "Optional pickled jalapeno slices", "Limes, for serving", " for serving", "Sour cream, for serving", " or , for serving"]}
{"name": "How to Grill Chicken Drumsticks", "ingredients": [" chicken drumsticks, (mine were about  each)", " extra virgin olive oil", " kosher salt", " freshly ground black pepper", "Vegetable oil for the grill grates", " of your favorite BBQ sauce (see  or )"]}
{"name": "Pork and Apple Skewers With Orange Balsamic Glaze", "ingredients": ["", " orange juice", " balsamic vinegar", " kosher salt", "\u2013 teaspoons freshly ground black pepper (depending on how peppery you\u2019d like your sauce)", "", " pounds pork tenderloin, silver skin removed", " Granny Smith apples", " extra virgin olive oil"]}
{"name": "Bananas Foster", "ingredients": ["", " ripe banana, well mashed", " granulated sugar", " dark rum", "(**Alternately, if you have a bottle of banana liquor on hand, use 1/4 cup)", "", " butter", " brown sugar", " ground cinnamon", " banana liquor from above", " firm peeled bananas cut in half across the center, then split in half the long way ( pieces per banana)", " dark rum", " *"]}
{"name": "Easy Grilled Shrimp", "ingredients": [" pounds large raw shell-on shrimp, 8-12 per pound", " extra virgin olive oil", " balsamic vinegar", " tomato paste", " Dijon mustard", " sesame oil", " celery salt", " freshly ground black pepper", " brown sugar", " paprika", " dry oregano", "Pinch of cayenne pepper, or to your taste", "Vegetable oil to oil the grill grates", "Optional: Cooked white rice, for serving"]}
{"name": "Chef\u2019s Salad", "ingredients": [" head romaine lettuce, chopped", "I small or half of large head of iceberg lettuce, chopped", " medium cucumber, peeled and sliced thin", "A few very thin slices of red onion", " small stalk of celery, cut into thin slices", "Few very thin slices of green bell pepper", " pound Black Forest ham, sliced \u00bc inch thick and cut into strips", " pound deli chicken or turkey, sliced \u00bc inch thick and cut into strips", " pound Swiss cheese, sliced \u00bc inch thick and cut into strips", " large ripe tomatoes, cut into  wedges each", "Three hard boiled eggs, cut into quarters ()", " pitted black olives", " Pepperoncini peppers", "Our Honey Dijon Ranch Dressing (see  or your favorite salad dressing)", "Slices of good crusty bread, for serving"]}
{"name": "S\u2019mores Cake", "ingredients": ["Vegetable shortening or butter and flour to grease and flour a ", " whole graham crackers", " all-purpose flour", " baking powder", " salt", " butter ( sticks), softened", " granulated sugar", " large eggs", " large egg yolks", " vanilla extract", " whole milk", " semisweet chocolate morsels", "", " butter ( sticks), softened", " confectioners\u2019 sugar", " vanilla extract", " marshmallow fluff", "Dark chocolate shavings, for garnish"]}
{"name": "Salmon Pasta Salad", "ingredients": [" cooked salmon (leftovers from  work great, or )", " pound box penne pasta, or other favorite pasta shape", " mayonnaise", " sour cream", " spicy brown mustard", " cider vinegar", " granulated sugar", " celery salt", " white pepper", " garlic powder", " frozen green peas, thawed", " red bell pepper, diced", " thinly sliced red onion, coarsely chopped"]}
{"name": "Grilled Basil Garlic Chicken Breasts", "ingredients": [" large boneless skin-on chicken breast halves (\u2013 ounces each)", " finely minced garlic", " kosher salt", " chopped fresh basil", " extra virgin olive oil", "Olive oil, salt and freshly ground black pepper for skin"]}
{"name": "Egg Roll in a Bowl", "ingredients": ["Optional, store-bought  (or buy fresh thin wonton wrappers, cut them into strips and fry your own)", "", " soy sauce", " rice vinegar", " honey", " ", " sesame oil", " granulated sugar", " corn starch", " water", "", " peanut oil, divided", " shiitake mushroom caps sliced thin", " pound ground pork", " finely minced ginger", " finely minced garlic", " sesame oil", " carrot, shredded through the large holes of a box grater", " daikon or red radish, shredded through large holes of a box grater", " scallions sliced ( in weight), whites and greens separate", " pound Napa cabbage, sliced (use mostly the leaf part and try to avoid too much stem) *", " soy sauce", " granulated sugar", " salt", " mung bean sprouts"]}
{"name": "Mediterranean Grilled Meatloaf", "ingredients": [" coarse dense bread cut into \u00bc inch cubes (You could use any hard-crusted loaf such as French or crusty Italian or bread like a country loaf)", "Zest of  large lemons", "Juice of  large lemons, \u00bd cup", " pounds 80/20 ground beef", " finely minced garlic", " fresh Italian flat leaf parsley, coarsely chopped (about  whole bunch without stems)", " eggs beaten, about \u2013 large eggs", " kosher salt", " white pepper", " freshly ground black pepper", " olive oil"]}
{"name": "Slow Cooker Creamy Tortellini and Sausage Soup", "ingredients": [" extra-virgin olive oil", " pounds sweet Italian sausage, removed from casing", " sweet onion, half inch dice", " carrots, half inch dice", " celery, quarter inch dice", " fresh garlic, minced", " chicken or vegetable stock or broth", " heavy cream", " cream cheese", " 14.5-ounce can diced tomatoes", " pound dry cheese tortellini", " baby spinach", " kosher salt", " white pepper", " dried basil", " dry oregano"]}
{"name": "Asian Chicken Lettuce Wraps", "ingredients": ["", " soy sauce", " Hoisin sauce", " sesame oil", " sherry wine", " honey", " ", " grated ginger", " grated fresh garlic", " cornstarch", "", " pounds mixed boneless skinless chicken breasts and thighs", " peanut oil, divided", "-ounce package shiitake mushrooms, stems discarded and caps thinly sliced", " bunch scallions, whites and tops sliced and separated", " red bell pepper sliced into short thin strips (about half of  large red bell pepper)", "", " radishes or daikon sliced into small matchstick pieces*", " dry roasted peanuts, coarsely chopped", " heads Boston Bibb lettuce or Butter lettuce"]}
{"name": "Slow Cooker Beef Barbacoa", "ingredients": ["\u2013 pounds chuck, cut into 3\u201d large pieces (I used  boneless chuck steaks that I found on sale but you could use any less-tender cuts of beef like top or bottom roasts or steaks. May require a longer cooking time if not using chuck)", " large or  medium garlic loves smashed", " 4-ounce cans ", " 4-ounce cans ", " large red onion, coarsely chopped", " fresh lime juice", " cider vinegar", " large bay leaves", " ground cumin", " ", " kosher salt", " freshly ground black pepper", " beef stock", " tomato paste", " dried , stem removed (available in most supermarkets)", " 6-inch flour tortillas, for serving", "Fresh cilantro, for garnish", "Limes wedges, for serving"]}
{"name": "Low Carb Chocolate Chocolate Chips", "ingredients": [" softened butter", " vegetable oil", " monk fruit, Stevia or xylitol sweeteners", " vanilla extract", " whole eggs", " of our ", " unsweetened cocoa powder", " salt", " baking powder", " dark chocolate chips"]}
{"name": "Onion Soup and Dip Mix", "ingredients": [" dried minced onion", " dry beef bouillon, low sodium if possible", " corn starch", " dry parsley flakes", " dried granulated garlic", " onion powder", " paprika", " sugar", " celery seed", " freshly ground black pepper"]}
{"name": "Mom\u2019s Meatloaf", "ingredients": [" country white bread cubed, crust removed, (about \u2013 slices), also see Tips & Tricks above", " whole milk", " pound ground beef (we used 80/20)", " pound ground pork", " whole eggs", " ", " Worcestershire sauce", " ketchup"]}
{"name": "Risotto Carbonara", "ingredients": [" extra-virgin olive oil", " bacon, diced", " sliced Genoa salami, diced", " chicken stock, homemade if possible", " butter", " onions, diced", " garlic, minced", "Pinch red pepper flakes", " Arborio rice", " white wine", " egg yolks", " heavy cream", " freshly grated Parmesan cheese", " freshly grated Romano cheese", " Italian flat leaf parsley, chopped", " white pepper", "Salt as needed (depending on how salty your stock is)"]}
{"name": "Homemade Chicken Stock", "ingredients": [" whole 4-5-pound frying chicken or fowl, gizzards discarded", " chicken feet, or  chicken wings, or  turkey wing", " large or  small turkey necks, or  turkey leg", " cloves garlic, peeled and crushed", " large Spanish onion cut in quarters (don\u2019t use sweet onion)", " large carrots cut into chunks about 1 \u00bd cups (peel only if the skin is dark or dirty)", " large stalks celery cut into chunks, about ", "Few celery leaves", " kosher salt", " whole black peppercorns", " bay leaves", " small bunch of flat leaf parsley", "\u2013 quarts cold water (enough to cover)"]}
{"name": "Milk and Cookies Dessert Flight", "ingredients": ["", "6 tablespoons softened butter", "\u00bd cup plus 2 tablespoons granulated sugar (10 tablespoons)", "3 tablespoons vegetable oil", "\u00bd cup plus 2 tablespoons brown sugar (10 tablespoons)", "\u00bd teaspoon salt", "2 teaspoons baking soda", "2 \u00bc cups all-purpose flour", "", "*2 eggs beaten which will not be added to starter mix but divided between the four cookie doughs*", "", "\u00bc of the starter mix from above (a little over one cup)", "1 tablespoon unsweetened cocoa powder", "\u00bc of the egg mixture (half of one large egg weighs just under one ounce)", "1 \u00bd teaspoons water", "1 \u00bd tablespoons vegetable oil", "\u00bd teaspoon vanilla extract", "", "\u00bc of the starter mix from above (a little over one cup)", "\u00bc of the egg mixture (half of one large egg weighs just under one ounce)", "2 teaspoons vegetable oil", "\u00bd teaspoon vanilla extract", "2 tablespoons mini chocolate chips", "2 tablespoons finely chopped walnuts", "", "\u00bc of the starter mix from above (a little over one cup)", "1 tablespoon all-purpose flour", "\u00bc teaspoon baking soda", "\u00bc of the egg mixture (half of one large egg weighs just under one ounce)", "\u00bc cup chunky peanut butter, any brand", "1 tablespoon vegetable oil", "\u00bd teaspoon vanilla extract", "", "\u00bc of the starter mix from above (a little over one cup)", "Zest from half a lemon", "\u00bd teaspoon corn starch", "\u00bc of the egg mixture (half of one large egg weighs just under one ounce)", "1 tablespoon melted butter", "4 drops yellow food color", "1 tablespoon lemon juice", "\u00bc teaspoon lemon extract", "\u00bd teaspoon honey", "", "Chocolate Cookie Cups", "", "Chocolate Chip Cookie Cups", ""]}
{"name": "Bacon Cheeseburger Lasagna", "ingredients": [" extra virgin olive oil", " onions, diced", " garlic, minced", " pounds 80/20 ground beef (don\u2019t worry, fat will be drained off after cooking)", " ketchup", " spicy brown mustard (we use )", " pound bacon", " pound lasagna noodles ( strips)", " pounds whole milk ricotta cheese", " whole eggs, beaten", " chopped fresh flat leaf parsley", " kosher salt", " freshly ground black pepper", " Monterey Jack cheese, shredded", " pound sharp white cheddar cheese, shredded", " pound white American sliced cheese (use real American cheese and not the brands that say \u201ccheese food\u201d)", " tomato sauce", "", "Diced dill pickles", "Diced fresh tomatoes", "Diced red onion", "Shredded iceberg lettuce"]}
{"name": "Cherry Noble BBQ Sauce", "ingredients": [" 6-ounce cans tomato paste", " molasses", " brown sugar", " grape jelly", " water", " cider vinegar", " kosher salt", " freshly ground black pepper", " dry mustard powder (we used \u2018s)", " dry ground ginger", " garlic powder", " onion powder"]}
{"name": "Fettuccine Alfredo", "ingredients": [" dry fettuccine pasta", " whole milk", " heavy cream", " butter", " garlic, finely minced", " all-purpose flour", " kosher salt", " white pepper", " dry mustard powder", "Few grinds fresh nutmeg", " freshly grated Parmesan cheese plus more for serving", "Optional \u2013 chopped parsley (for garnish)"]}
{"name": "The Real IKEA Swedish Meatballs Recipe", "ingredients": ["", " pounds ground beef 85/15", " pound finely ground pork", " onion, finely diced", " fresh garlic, finely minced", " plain bread crumbs", " whole eggs", " whole milk", " kosher salt", " freshly ground black pepper", " olive oil, divided", "", " vegetable stock", " beef stock", " heavy cream", " soy sauce", " Dijon mustard", " olive oil", " butter", " all-purpose flour", "", "", "", ""]}
{"name": "Macaroni Salad", "ingredients": [" hard-boiled eggs, ", " kosher salt to salt the pasta water", " dry Cavatappi or elbow noodles", " good quality mayonnaise, ", " sour cream", " spicy brown mustard", " cider vinegar", " celery, finely diced", " sweet onion, finely diced", " dill pickles, diced medium and drained", " red bell pepper, diced medium", " celery salt", " granulated sugar", " garlic powder", " white pepper", "Optional: See Notes below for other ingredients you could add to your macaroni salad."]}